### PR TITLE
Fix and add a spec for international text chunks

### PR DESCRIPTION
**Pull request by chrisseaton**

### CODE REVIEW

**Comment by wvanbergen** [comment]
👌 

Should we be doing anything here when we have multiple chunks for the same keyword, in different languages?

**Comment by chrisseaton** [comment]
Sorry I've no idea about what these chunks do or the PNG spec or anything really. Almost all PNGs I've been trying to load failed without this fix though - maybe it's because I'm in a non-US locale I get these chunks and you don't?

**Comment by chrisseaton** [comment]
Is it possible to merge this, then?

**Comment by wvanbergen** [comment]
I applied an alternative fix (forgot about this PR existing). The applied fix is arguably not as nice as this solution, so I am happy to merge this, if it is rebased and addresses the multiple keywords issue.

**Comment by chrisseaton** [comment]
Closing this because I can't even remember what it was and I seem to have deleted the fork and the local checkout. I'll see if it exists next time I use the gem. Thanks.

**Pull request closed without merging**
